exclude_paths:
  - tmp
  - vendor

detectors:
  FeatureEnvy:
    exclude:
      - Wholable::Equatable#included
  LongParameterList:
    enabled: false
  NestedIterators:
    exclude:
      - Wholable::Equatable#define_diff
  TooManyStatements:
    exclude:
      - Wholable::Equatable#define_diff
      - Wholable::Equatable#define_inspect
