exclude_paths:
  - tmp
  - vendor

detectors:
  LongParameterList:
    enabled: false
  NestedIterators:
    exclude:
      - "Wholable::Equatable#define_diff"
  ModuleInitialize:
    exclude:
      - "Wholable::Freezable"
  TooManyStatements:
    exclude:
      - "Wholable::Equatable#define_diff"
      - "Wholable::Equatable#define_instance_methods"
      - "Wholable::Equatable#define_inspect"
  UtilityFunction:
    exclude:
      - "Wholable::Equatable#define_deconstruct"
      - "Wholable::Equatable#define_deconstruct_keys"
