exclude_paths:
  - tmp
  - vendor

detectors:
  FeatureEnvy:
    exclude:
      - Wholable::Equatable#define_class_methods
  LongParameterList:
    enabled: false
  NestedIterators:
    exclude:
      - Wholable::Equatable#define_diff
  ModuleInitialize:
    exclude:
      - Wholable::Freezable
  TooManyStatements:
    exclude:
      - Wholable::Equatable#define_diff
      - Wholable::Equatable#define_instance_methods
      - Wholable::Equatable#define_inspect
