exclude_paths:
  - tmp
  - vendor

detectors:
  LongParameterList:
    enabled: false
  ModuleInitialize:
    exclude:
      - "Wholable::Freezable"
  TooManyStatements:
    exclude:
      - "Wholable::Equatable#define_inspec"
